### ISSUE TITLE
add SPM Support

### ISSUE THREAD

**Issue by lorenzofiamingo** [rever-ai/CombineFirebase#8]
https://github.com/tomatrow/CombineFirebase

**Comment by mobiletoly** [comment]
Yes, please, that would be great.

**Comment by kshivang** [comment]
Follow this: https://github.com/firebase/firebase-ios-sdk/issues/3136
firebase-ios-sdk is the bottleneck currently

**Comment by mobiletoly** [comment]
Thank you, @kshivang 

Yes, it is a bottleneck, but one work-around could be that CombineFirebase does not need to add Firebase dependency and let developer figure out how to add Firebase to the project. For example I use a combination of Carthage and SPM. My Cartfile contains something like this:

    binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
    binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
    binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseFirestoreBinary.json"
    binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseStorageBinary.json"
    binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json"

to include Firebase and for SPM I use https://github.com/tomatrow/CombineFirebase fork of your code that @lorenzofiamingo  posted here, because he already added Package.swift in there. So this combination works great. I guess you could just copy Package.swift from his repository to yours and it will work.

**Comment by tomatrow** [comment]
@lorenzofiamingo  Yeah, I couldn't get it working.

**Comment by quanshousio** [comment]
@kshivang I just implemented support for SPM in #10, would you mind checking it out?

**Comment by kshivang** [comment]
@quanshousio Sure looking into it

**Comment by dchakarov** [comment]
I tried adding using SPM and got this error: 
`https://github.com/rever-ai/CombineFirebase has no Package.swift manifest for version 0.2.6`
Is there something I'm missing?

**Comment by quanshousio** [comment]
@kshivang Can you tag the latest commit? If someone adds the package using version rules, Xcode will only fetch that repo up until the tagged commit.

@dchakarov For now, you can add the package using branch `master`.

**Comment by quanshousio** [comment]
@kshivang Can you tag the latest commit? If someone adds the package using version rule, Xcode will only fetch that repo up until the tagged commit.

@dchakarov For now, you can add the package using branch `master`.

**Comment by dchakarov** [comment]
@quanshousio using "master" seemed to work, thank you 💯
